"""empty message

Revision ID: 9ac25989feeb
Revises: 6fc994d2b91b
Create Date: 2020-11-09 19:54:03.576036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac25989feeb'
down_revision = '6fc994d2b91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('gamer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gamer_id'], ['gamers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###
